// src/index.ts
// Venice AI MPP Proxy — full service implementation
//
// Exposes Venice AI's OpenAI-compatible API behind the Machine Payments Protocol.
// Clients pay in PathUSD on Tempo:
//   - Chat completions: per-session via MPP sessions (off-chain EIP-712 vouchers)
//   - Images / audio / embeddings: one-time on-chain charge per request
//
// Discovery endpoints (auto-generated by mppx/proxy):
//   GET /discover            → JSON service catalog
//   GET /llms.txt            → plain-text catalog for LLM agents
//   GET /discover/venice.md  → Markdown route docs

import { Proxy, Service } from 'mppx/proxy'
import { Mppx, tempo } from 'mppx/server'

// --- Environment validation ---

const PATHUSD = (process.env.PAYMENT_CURRENCY ??
  '0x20c0000000000000000000000000000000000000') as `0x${string}`

const recipient = process.env.RECIPIENT_ADDRESS as `0x${string}`
if (!recipient) throw new Error('Missing required env var: RECIPIENT_ADDRESS')

const veniceApiKey = process.env.VENICE_API_KEY
if (!veniceApiKey) throw new Error('Missing required env var: VENICE_API_KEY')

const port = Number(process.env.PORT ?? 3001)

// --- Payment methods ---
// tempo() returns [charge, session] — Mppx exposes mppx.charge() and mppx.session()
// MPP_SECRET_KEY is auto-detected from env by Mppx.create()

const mppx = Mppx.create({
  methods: [tempo({ currency: PATHUSD, recipient })],
})

// --- Proxy config ---
// Service ID is 'venice' — routes are mounted at /venice/v1/...

const proxy = Proxy.create({
  title: 'Venice AI',
  description:
    'MPP-gated proxy for Venice AI inference APIs. Pay per session for chat ' +
    'completions via sessions; flat fee for images, audio, and embeddings.',
  services: [
    Service.from('venice', {
      bearer: veniceApiKey,
      baseUrl: 'https://api.venice.ai/api',
      description: 'Chat completions, embeddings, image generation, and audio transcription.',
      title: 'Venice AI',
      routes: {
        // Session-based per-voucher billing — ideal for streaming chat
        'POST /v1/chat/completions':   mppx.session({ amount: '0.0001' }),
        // Flat charge per request — images are expensive and non-streaming
        'POST /v1/images/generations': mppx.charge({ amount: '0.05' }),
        // Flat charge per TTS request
        'POST /v1/audio/speech':       mppx.charge({ amount: '0.02' }),
        // Flat charge per embedding batch — embeddings are cheap
        'POST /v1/embeddings':         mppx.charge({ amount: '0.005' }),
        // Free passthrough — no reason to gate model listing
        'GET /v1/models':              true,
      },
    }),
  ],
})

// --- Start server ---

Bun.serve({ port, fetch: proxy.fetch })

console.log(`Venice MPP proxy running on http://localhost:${port}`)
console.log(`Paid routes mounted at: /venice/v1/...`)
console.log(`Discovery: http://localhost:${port}/discover`)
console.log(`LLM agents: http://localhost:${port}/llms.txt`)
